src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="text")
     */
    private $contenu;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_pub;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $auteur;

    
    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

   

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $image;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="article")
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity=Picture::class, mappedBy="article", orphanRemoval=true)
     */
    private $pictures;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->pictures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getDatePub(): ?\DateTimeInterface
    {
        return $this->date_pub;
    }

    public function setDatePub(\DateTimeInterface $date_pub): self
    {
        $this->date_pub = $date_pub;

        return $this;
    }

    public function getAuteur(): ?string
    {
        return $this->auteur;
    }

    public function setAuteur(?string $auteur): self
    {
        $this->auteur = $auteur;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

  

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Picture>
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setArticle($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->removeElement($picture)) {
            // set the owning side to null (unless already changed)
            if ($picture->getArticle() === $this) {
                $picture->setArticle(null);
            }
        }

        return $this;
    }

    
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('contenu')
            ->add('category')
            ->add('image', FileType::class,
            [   
                'label' =>'Chargez une image',
                'data_class' => null,
                'required' => false
            ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/article")
 */
class ArticleController extends AbstractController
{
    /**
     * @Route("/", name="article_index", methods={"GET"})
     */
    public function index(ArticleRepository $articleRepository): Response
    {
        return $this->render('article/index.html.twig', [
            'articles' => $articleRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="article_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // je récupére le fichies passé dans le form
            $image = $form->get('image')->getdata();
            // si il y a une image de chargée
            if ($image) {
                // je crée un nom unique pour cette image et je remet l'extension
                $img_file_name = uniqid() . '.' . $image->guessExtension();
                // enregistrer le fichier dans le dossier image 
                $image->move($this->getParameter('upload_dir'), $img_file_name);
                // je set l'object article
                $article->setImage($img_file_name);
            } else {
                // si $image = null je set l'image par default
                $article->setImage('defaultimg.jpg');
            }


            // je récupére la date du jour 
            $date_jour = new DateTime();
            // je set la propriété date_pub de l'object article avant d'enregistrer en BDD 
            $article->setDatePub($date_jour);
            // je set la propriété auteur avec 'admin' 
            $auteur = 'admin';
            $article->setAuteur($auteur);

            // j'enregistre en BDD 
            $entityManager->persist($article);
            $entityManager->flush();

            return $this->redirectToRoute('article_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('article/new.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="article_show", methods={"GET"})
     */
    public function show(Article $article): Response
    {
        return $this->render('article/show.html.twig', [
            'article' => $article,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="article_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Article $article, EntityManagerInterface $entityManager): Response
    {

        // je récupére l'ancien nom de l'image avant qu'il ne soit effacé
        $old_name_img = $article->getImage();
        // création du formulaire
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // je récupére le fichies passé dans le form
            $image = $form->get('image')->getdata();
            // si il y a une image de chargée
            if ($image) {
                // je crée un nom unique pour cette image et je remet l'extension
                $img_file_name = uniqid() . '.' . $image->guessExtension();
                // enregistrer le fichier dans le dossier image 
                $image->move($this->getParameter('upload_dir'), $img_file_name);
                // je set l'object article
                $article->setImage($img_file_name);
                $name_file_delete = $this->getParameter('upload_dir') . $old_name_img;
                if (file_exists($name_file_delete) && is_file($name_file_delete)) {
                    unlink($name_file_delete);
                }
            } else {
                // si $image = null je setavec l'ancien nom 
                $article->setImage($old_name_img);
            }

            //________________ envoi a la BDD __________________________
            $entityManager->flush();

            return $this->redirectToRoute('article_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('article/edit.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="article_delete", methods={"POST"})
     */
    public function delete(Request $request, Article $article, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $article->getId(), $request->request->get('_token'))) {
            $entityManager->remove($article);
            $entityManager->flush();

            $old_name_img = $article->getImage();
            if ($old_name_img != 'defaultimg.jpg') {
                $name_file_delete = $this->getParameter('upload_dir') . $old_name_img;
                if (file_exists($name_file_delete) && is_file($name_file_delete)) {
                    unlink($name_file_delete);
                }
            }
        }



        return $this->redirectToRoute('article_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/article/_delete_form.html.twig
<form method="post" action="{{ path('article_delete', {'id': article.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn">Delete</button>
</form>

templates/article/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn-success m-2">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Article{% endblock %}

{% block body %}
    <h1>Edit Article</h1>

    {{ include('article/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('article_index') }}">back to list</a>

    {{ include('article/_delete_form.html.twig') }}
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article index{% endblock %}

{% block body %}
<style>
    /*.example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }*/
    table { margin:auto; max-width: 95%; }
    div.container { justify-content: center; max-width: 95%; }  
</style>

    <h1>&nbsp;&nbsp;Article index</h1>
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titre</th>
                <th>Contenu</th>
                <th>Date_pub</th>
                <th>Auteur</th>
                <th>Image</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for article in articles %}
            <tr>
                <td>{{ article.id }}</td>
                <td>{{ article.titre }}</td>
                <td>{{ article.contenu | slice(0, 300) }}</td>
                 <td>{{ article.datePub ? article.datePub|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ article.auteur }}</td>
                     <td><img src="{{ asset('assets/images/' ~ article.image)}}" alt="" style="width:80px"></td>
            
                <td>
                    <a href="{{ path('article_show', {'id': article.id}) }}">show</a>
                    <a href="{{ path('article_edit', {'id': article.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('article_new') }}">Create a new article</a>
    </div>
{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article{% endblock %}

{% block body %}
    <h1>Article</h1>

<div class="row">
<div class="col-8">
<table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ article.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ article.titre }}</td>
            </tr>
            <tr>
                <th>Contenu</th>
                <td>{{ article.contenu }}</td>
            </tr>
            <tr>
                <th>Date_pub</th>
                <td>{{ article.datePub ? article.datePub|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
           
            <tr>
                <th>Photo</th>
                <td>{{ article.auteur }}</td>
                <td><img src="{{ asset('assets/images/' ~ article.image)}}" alt="" style="width:300px"></td>
                </tr>

        </tbody>
    </table>
</div>
<div class="col-4">

{% for item in article.pictures %}
<div>
<img src="{{ asset('assets/images/' ~ item.name)}}"
alt="{{ item.alt }}" style="width:150px">
<a href="{{ path('picture_delete' , {'id' : item.id}) }}">Supprimer</a>

</div>
  {% endfor %}
 


<div>
    <a href="{{ path('article_index') }}">back to list</a>
    <a href="{{ path('article_edit', {'id': article.id}) }}" class="">edit</a>
    <a href="{{ path('picture_new', {'id': article.id}) }}" class="btn btn-secondary">Ajouter une image</a>

    {{ include('article/_delete_form.html.twig') }}
    </div>

{% endblock %}